//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gitara.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towar
    {
        public int TowarId { get; set; }
        public string Producent { get; set; }
        public decimal Cena { get; set; }
        public string Model { get; set; }
        public string Opis { get; set; }
        public int KategoriaId { get; set; }
    }
}
